# Generated by Django 5.2 on 2025-05-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
