# Generated by Django 5.2 on 2025-05-11 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_alter_patientprofile_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="Дата приема"),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время приема"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Длительность приема (мин)"
                    ),
                ),
                (
                    "is_booked",
                    models.BooleanField(default=False, verbose_name="Занято"),
                ),
            ],
            options={
                "ordering": ["date", "time"],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Отчество"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(max_length=100, verbose_name="Специальность"),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(verbose_name="Стаж (в годах)"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="doctors/photos/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system.patientprofile",
                    ),
                ),
                (
                    "slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system.appointmentslot",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointmentslot",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="system.doctor",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointmentslot",
            unique_together={("doctor", "date", "time")},
        ),
    ]
